<?php
return[
    "es"=>[
        "name"=>"Español",
        "flag"=>"🏴🇪🇸",
    ],
    "fr"=>[
        "name"=>"France",
        "flag"=>"🏳️🇫🇷",
    ],
    "en"=>[
        "name"=>"Enghis",
        "flag"=>"🚩🇬🇧",
    ],
];
?>